### ISSUE TITLE
Backup to AWS not working since update of Spilo

### ISSUE THREAD

**Issue by daniel-gut-ricardo** [ricardo-ch/platform-postgres-spilo#1]
Pods log following regarding Backup:

```        STRUCTURED: time=2018-03-21T07:47:39.343665-00 pid=132
2018-03-21 07:47:39.396 - /postgres_backup.sh - producing a new backup
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2018-03-21T07:47:39.935934-00 pid=26
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to s3://platform-dev-postgres/spilo/postgres-tst-backuptest/wal/basebackups_005/base_000000010000000000000002_00000040/extended_version.txt.
        STRUCTURED: time=2018-03-21T07:47:44.340113-00 pid=26
2018-03-21 07:47:56,068 INFO: Lock owner: tst-backuptest-0; I am tst-backuptest-0
2018-03-21 07:47:56,080 INFO: no action.  i am the leader with the lock
2018-03-21 07:48:06,069 INFO: Lock owner: tst-backuptest-0; I am tst-backuptest-0
2018-03-21 07:48:06,086 INFO: no action.  i am the leader with the lock
[...]
wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2018-03-21T07:49:03.547588-00 pid=26
2018-03-21 07:49:06,070 INFO: Lock owner: tst-backuptest-0; I am tst-backuptest-0
2018-03-21 07:49:06,121 INFO: no action.  i am the leader with the lock
NOTICE:  pg_stop_backup cleanup done, waiting for required WAL segments to be archived
2018-03-21 07:49:26,067 INFO: Lock owner: tst-backuptest-0; I am tst-backuptest-0
2018-03-21 07:49:26,079 INFO: no action.  i am the leader with the lock
[...]
2018-03-21 07:52:56,066 INFO: Lock owner: tst-backuptest-0; I am tst-backuptest-0
2018-03-21 07:52:56,075 INFO: no action.  i am the leader with the lock
WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (240 seconds elapsed)
HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
```

**Comment by cmeury** [comment]
A bit earlier is also interesting:

```
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python3.5/dist-packages/wal_e/cmd.py", line 694, in main
            args.NUM_TO_RETAIN)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/operator/backup.py", line 423, in delete_with_retention
            delete_cxt.delete_with_retention(num_to_retain)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/worker/base.py", line 446, in delete_with_retention
            for key in self._backup_list(prefix=self.layout.basebackups()):
          File "/usr/local/lib/python3.5/dist-packages/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
            encoding_type=encoding_type)
          File "/usr/local/lib/python3.5/dist-packages/boto/s3/bucket.py", line 474, in get_all_keys
            '', headers, **params)
          File "/usr/local/lib/python3.5/dist-packages/boto/s3/bucket.py", line 400, in _get_all
            query_args=query_args)
[...]
2018-03-21 07:47:39.396 - /postgres_backup.sh - producing a new backup
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2018-03-21T07:47:39.935934-00 pid=26
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to s3://platform-dev-postgres/spilo/postgres-tst-backuptest/wal/basebackups_005/base_000000010000000000000002_00000040/extended_version.txt.
        STRUCTURED: time=2018-03-21T07:47:44.340113-00 pid=26
wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2018-03-21T07:49:03.547588-00 pid=26
```

**Comment by cmeury** [comment]
I'll try to reproduce that locally with the same spilo container and env configuration.

**Comment by cmeury** [comment]
Not much, but at least something. I can reproduce this error by exec'ing into the pod:

```
# su postgres -c "PATH=$PATH /patroni_wait.sh -t 10 -- /postgres_backup.sh $WALE_ENV_DIR $PGDATA"
2018-03-21 12:57:48.979 - /postgres_backup.sh - I was called as: /postgres_backup.sh /home/postgres/etc/wal-e.d/env /home/postgres/pgdata/pgroot/data
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "delete retain".
        STRUCTURED: time=2018-03-21T12:57:49.549533-00 pid=5947
wal_e.main   INFO     MSG: deleting data in the store
        STRUCTURED: time=2018-03-21T12:57:49.636762-00 pid=5947

[90 seconds waiting time]

wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python3.5/dist-packages/wal_e/cmd.py", line 694, in main
            args.NUM_TO_RETAIN)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/operator/backup.py", line 423, in delete_with_retention
            delete_cxt.delete_with_retention(num_to_retain)
          File "/usr/local/lib/python3.5/dist-packages/wal_e/worker/base.py", line 446, in delete_with_retention
            for key in self._backup_list(prefix=self.layout.basebackups()):
          File "/usr/local/lib/python3.5/dist-packages/boto/s3/bucketlistresultset.py", line 34, in bucket_lister
            encoding_type=encoding_type)
          File "/usr/local/lib/python3.5/dist-packages/boto/s3/bucket.py", line 474, in get_all_keys
            '', headers, **params)
          File "/usr/local/lib/python3.5/dist-packages/boto/s3/bucket.py", line 400, in _get_all
            query_args=query_args)
          File "/usr/local/lib/python3.5/dist-packages/boto/s3/connection.py", line 671, in make_request
            retry_handler=retry_handler
          File "/usr/local/lib/python3.5/dist-packages/boto/connection.py", line 1071, in make_request
            retry_handler=retry_handler)
          File "/usr/local/lib/python3.5/dist-packages/boto/connection.py", line 1030, in _mexe
            raise ex
          File "/usr/local/lib/python3.5/dist-packages/boto/connection.py", line 943, in _mexe
            request.body, request.headers)
          File "/usr/lib/python3.5/http/client.py", line 1106, in request
            self._send_request(method, url, body, headers)
          File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
            self.endheaders(body)
          File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
            self._send_output(message_body)
          File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
            self.send(msg)
          File "/usr/lib/python3.5/http/client.py", line 877, in send
            self.connect()
          File "/usr/lib/python3.5/http/client.py", line 1252, in connect
            super().connect()
          File "/usr/lib/python3.5/http/client.py", line 849, in connect
            (self.host,self.port), self.timeout, self.source_address)
          File "/usr/local/lib/python3.5/dist-packages/gevent/socket.py", line 77, in create_connection
            for res in getaddrinfo(host, port, 0 if has_ipv6 else AF_INET, SOCK_STREAM):
          File "/usr/local/lib/python3.5/dist-packages/gevent/_socketcommon.py", line 288, in getaddrinfo
            return get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
          File "/usr/local/lib/python3.5/dist-packages/gevent/resolver_thread.py", line 65, in getaddrinfo
            return self.pool.apply(_socket.getaddrinfo, args, kwargs)
          File "/usr/local/lib/python3.5/dist-packages/gevent/pool.py", line 325, in apply
            return self.spawn(func, *args, **kwds).get()
          File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 385, in get
            return self.get(block=False)
          File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 375, in get
            return self._raise_exception()
          File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 355, in _raise_exception
            reraise(*self.exc_info)
          File "/usr/local/lib/python3.5/dist-packages/gevent/_compat.py", line 33, in reraise
            raise value.with_traceback(tb)
          File "/usr/local/lib/python3.5/dist-packages/gevent/threadpool.py", line 211, in _worker
            value = func(*args, **kwargs)
        socket.gaierror: [Errno -2] Name or service not known

        STRUCTURED: time=2018-03-21T12:59:05.134243-00 pid=5947
2018-03-21 12:59:05.170 - /postgres_backup.sh - producing a new backup
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "backup-push".
        STRUCTURED: time=2018-03-21T12:59:05.713853-00 pid=5932
wal_e.operator.backup INFO     MSG: start upload postgres version metadata
        DETAIL: Uploading to s3://platform-dev-postgres/spilo/postgres-tst-backuptest/wal/basebackups_005/base_000000010000000000000010_00000040/extended_version.txt.
        STRUCTURED: time=2018-03-21T12:59:06.827640-00 pid=5932
wal_e.operator.backup WARNING  MSG: blocking on sending WAL segments
        DETAIL: The backup was not completed successfully, but we have to wait anyway.  See README: TODO about pg_cancel_backup
        STRUCTURED: time=2018-03-21T13:00:29.557724-00 pid=5932
NOTICE:  pg_stop_backup cleanup done, waiting for required WAL segments to be archived
WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (60 seconds elapsed)
HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (120 seconds elapsed)
HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
^C
```

So, here's what I understand happens, from that log:

* We call [`wal-e delete retain`](https://pypi.python.org/pypi/wal-e/1.1.0) with a retain value of 2 (leave at least 2 base backups before creating a new one). This results in an *error*: `socket.gaierror: [Errno -2] Name or service not known` - interesting!
* We call `wal-e backup-push`, pointing it to the persistent volume mounted at  `/home/postgres/pgdata/pgroot/data` and these environment variables:
  * TMPDIR=/home/postgres/pgdata/tmp
  * WALE_S3_ENDPOINT=https+path://s3-loca.amazonaws.com:443
  * WALE_S3_PREFIX=s3://platform-dev-postgres/spilo/postgres-tst-backuptest/wal/
* The `backup-push` command fails to properly upload the WAL segments: `The backup was not completed successfully, but we have to wait anyway.`

**Comment by cmeury** [comment]
Something immediately suspicious is:
    WALE_S3_ENDPOINT=https+path://s3-loca.amazonaws.com:443
The hostname `s3-loca.amazonaws.com` does not resolve, explaining the error message of the `delete retain` command, and maybe the failing `backup-push` is just a consequence of still waiting for the delete command. Or the error is not shown in the log.

According to the wal-e documentation:
> If one wishes to target WAL-E against an alternate S3 endpoint (e.g. Ceph RADOS), one can set the WALE_S3_ENDPOINT environment variable.

I don't think we want that, so this looks to have been smuggled in.

**Comment by cmeury** [comment]
Found the problem while pairing with @daniel-gut-ricardo:

So far we have been using "platform-dev-postgres" as the value for `WAL_S3_BUCKET`. When the following [code]() extracts the region, we fail to match and fall-back onto the default value of `placeholders['instance_data']['zone']` minus the last characters. This results in the weird hostname I've seen above: "s3-loca.amazonaws.com"

```python
match = re.search(r'.*(eu-\w+-\d+)-.*', wale['WAL_S3_BUCKET'])
if match:
    region = match.group(1)
else:
    region = placeholders['instance_data']['zone'][:-1]
```

We constructed a bucket name that will conform to the given regular expression: `eu-west-1-platform-dev-postgres`. A new bucket was created (being in the `eu-west-1` region so spilo queries the correct hostname).

**Comment by cmeury** [comment]
Good! Let's close this and track further changes in internal repositories.

```$ aws s3 --profile=spilo-dev ls  s3://eu-west-1-platform-dev-postgres/spilo/postgres-CLUSTERNAME/wal/basebackups_005/base_0000007E00000013000000D0_00000040/
                           PRE tar_partitions/
2018-03-21 15:57:04        140 extended_version.txt
```
